# Generated by Django 4.2.1 on 2023-05-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlcommon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='qq',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
